# Base configs
baseurl: "https://www.gustav.tech/Cheria/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics:

# UI configs
title: "Cheria Portfolio"
subtitle: "My work"
author:
header:
 title: "Ch√©ria's Portfolio"
 subtitle:
footer:
 name: "About me"
 bio: "My name is Cheria Essieke, I am born in 1993 and is originally from the Republic of Congo. Next to modelling I am studying Political Science in Germany and working on empowering Afro culture via www.newafro.global"               
web_design: 
social_urls:
  facebook:
  twitter: 
  instagram: "https://www.instagram.com/cheria_essieke/"
  dribbble: 
  linkedin: 
  github:
